<% ==Party Details== [[dOrg "Name of the decentralized organization (dOrg)/LLC?"]] [[Client "Name of the Client?"]]

==Legal Details== [[State: Choice("Wyoming", "Delaware", "Vermont")]] [[State Selection: State]] %>

\centered dOrg Standard Terms & Conditions

These [[dOrg]] Standard Terms & Conditions apply to services & deliverables (collectively, “Projects” &, singly, a “Project”) commissioned through the [[dOrg]] LLC DAO (the “DAO”). By transacting through the DAO, the commissioning party [[Client]] (the “Client”) agrees to be bound by these [[dOrg]] Standard Terms & Conditions, which, together with the Statement of Work (“SOW”) defined herein, will constitute the full & complete agreement between [[dOrg]] (“dOrg”) & the [[Client]] relating to the Project. Each of [[dOrg]] and [[Client]] may be individually referred to as a "Party" or collectively referred to as the "Parties" as the context may require.

Definitions:

^^ “Project” means the services & deliverables specified in the SOW & any additional written scoping documents agreed between the Parties.

^^ “Contractor” means an independent contractor & member of the DAO.

^ Section 1 Submission & Approval of SOW & Project. The SOW will define the scope of the Project & all of the parameters for its performance as per the template SOW provided above or as otherwise provided by dOrg. Each Project must be approved by the DAO voting protocol. Any subsequent changes to the Project or the SOW will require the approval of the DAO & may result in additional &/or pro-rated Fees.

^ Section 2 Intellectual Property Rights. Upon full payment of all Fees, dOrg will transfer all rights, title & interest in all code & assign all intellectual property rights (IPR) in the Project to the Client ("New IP"). dOrg will obtain a limited license to use the New IP for internal business purposes only & otherwise to perform the Agreement. dOrg retains ownership of all IPR in all work created, conceived or implemented by dOrg prior to or independently of the Project ("Background IP"). To the extent any Background IP is incorporated into any Project deliverable, dOrg grants Client a perpetual, irrevocable, royalty free, transferable, sub-licensable, worldwide, non-exclusive licence to use such Background IP solely as incorporated into the Project deliverables. dOrg undertakes to take such reasonable steps & execute such documents reasonably necessary to perfect the Client's ownership of the New IP as reasonably requested by & at Client's cost.

^ Section 3 Fees & Payment. In consideration for provision of the Services the Client shall pay dOrg the Fees in accordance with the Payment Schedule & via the payment method as set out in the SOW. dOrg will invoice Client a minimum of 1 week prior to the payment date. The Fees will be payable in the currencies specified in the SOW & any amount converted from one currency to another will be equivalent to the Fees as stated in USD as determined by the spot price 5 business days prior to payment due date as published by coinmarketcap.com. Client agrees to make full payment of the Fees by the specified payment date except any payments or part thereof subject to a bona fide dispute.

^^ Section 3.1 Disputes & Late Payments. If Client alleges a bona fide dispute as to payment of the Fees, Client will pay the undisputed portion on the due date & will notify dOrg of the reasons for disputing the remainder of the payment as soon as possible. Disputes relating to payments will be resolved as quickly as possible pursuant to s12.1 (Disputes). dOrg reserves the right to charge a late payment fee of 1.5 percent per month, or the maximum permitted by applicable law, whichever is less, on all amounts remaining unpaid for a period of 30 days after they become due & payable.

^^ Section 3.2 Expenses & Taxes. dOrg will be responsible for all their expenses related to providing the Services under this Agreement. Client is responsible for paying any sales taxes, use taxes, or other applicable taxes related to the receipt of services &/or the Services. Client is not responsible for withholding or paying any income taxes, employment or payroll-related taxes related to the work of dOrg or its Contractors.

^^ Section 3.3 Changes to the Services or the Fees. Any changes in the scope of the Services shall be subject to the mutual agreement of the Parties & may result in pro-rated fees. In the event of early termination of the Agreement, payment of the Fees will be adjusted as set out in s7.

^ Section 4 Limitation on Liability. In the event of a dispute between the parties that results in a judgment, award, settlement, or agreement in favor of Client, the maximum amount of damages dOrg will be liable to pay Client is a full refund of all payments Client has made to date for the Project(s) at issue. Neither dOrg nor Contractors shall be liable for any incidental, consequential, indirect or punitive damages, or loss of profit, revenue, or business for any reason, including, but not limited to (i) access to, use of, or inability to use the DAO or any information, services or content available therein; (ii) the breach of any covenant, representation or warranty; (iii) the use or downloading of any software or application owned or operated by the DAO or any third party, in connection with the DAO; or (iv) any errors or omissions in the information, services or content therein, whether based on warranty, contract, negligence, tort, or any other legal theory, & whether or not dOrg or any Contractor was advised of the possibility of such damages. This limitation includes, but is not limited to, personal injury & personal property damages.

^ Section 5 Termination. All Projects are subject to termination by either dOrg or the Client, upon reasonable notice to the other party. Both dOrg & Client agree that, where feasible, they will notify the other party of any performance concerns prior to terminating, in order to provide the non-terminating party an opportunity to cure (e.g. to complete performance, submit payment, provide a necessary software license, etc.). Nonetheless, dOrg may terminate a Project for reasons including, but not limited to, Client’s failure to timely pay or to provide any necessary information, approvals, review, or software licenses. Likewise, Client may terminate for reasons including, but not limited to, failure of dOrg &/or Contractor(s) to timely perform or complete the Project or to produce satisfactory Services. For any Project terminated before completion, Client will make a partial payment to dOrg for the value of Services rendered as of the termination date, such value to be determined as a pro rata portion of the Fees. If Client prepayments exceed the value of the partially-completed Project, dOrg will refund the amount of prepaid funds that exceeds the value of Services provided to Client.

^ Section 6 Indemnification. Client agrees to defend, indemnify & hold harmless dOrg & its Contractors, & each of their respective members, administrative members, managers, administrative members, officers, directors, employees, agents, licensors, licensees, suppliers & third-party clients from & against all losses, expenses, damages & costs, including, without limitation, reasonable attorneys’ fees & accounting fees, resulting from (i) any violation of any third party rights, including, without limitation, any IP, copyright, trademark, property, publicity or privacy right by Client or at the direction of Client, pursuant to a SOW; (iii) Client’s breach of any representations, warranties &/or covenants contained herein; & (iii) Client’s direct use (if any) of the DAO.

^ Section 7 Non-Solicitation.* During the term of this Agreement and for a period of one year thereafter, Client shall not solicit, make an offer of employment to, or enter into a consulting relationship with, any member of dOrg during the period starting on the date of this Agreement and ending one year after its termination or expiration. If Client breaches this provision, Client shall pay to dOrg a fee equivalent to 20% of the member’s annual remuneration by the Client.

^ Section 8 Disputes & Arbitration.

^^ Section 8.1 Disputes. WIth respect to any dispute, controversy or claim arising out of, or in connection with, or relating to, this Agreement or any contract performed thereunder or any breach or alleged breach hereof, the Parties agree to notify the other promptly of such dispute & hold good faith negotiations amongst themselves before commencing any formal legal action or Arbitration.

^^ Section 8.2 Arbitration. Should good faith negotiations not resolve any dispute within 30 days then upon the written request of either party (Notice), such dispute shall be submitted to arbitration before a mutually agreed upon single arbitrator in Sacramento, California. The Parties shall agree on a single arbitrator within 30 days after Notice & if the parties cannot agree, each party shall choose an arbitrator, and the parties' arbitrators shall agree upon a single neutral arbitrator for the dispute. The arbitration shall proceed pursuant to this s7 & otherwise pursuant to the Commercial Arbitration Rules then in effect of the American Arbitration Association (or at any other place or under any other form of arbitration mutually acceptable to the parties so involved). Any award rendered shall be final & conclusive upon the parties & a judgment thereon may be entered in the appropriate court having jurisdiction thereof. The expenses of the arbitration shall be borne equally by the parties or as otherwise determined by the arbitrator. The parties shall use all reasonable efforts to ensure that the arbitration is completed as promptly as reasonably possible, & preferably within not more than ninety (90) days after either party’s request for arbitration hereunder.

^ Section 9 General Provisions

^^ Section 9.1 Confidentiality. Both parties agree not to use, copy or disclose the other party’s confidential information other than to the extent necessary to perform this Agreement.

^^ Section 9.2 Notice. Any notice required under this Agreement must be in writing & may be delivered via email or mail to the address specified in the SOW &/or otherwise customarily used by the receiving party & as updated by written notice from time to time. Emails will be deemed communicated 1 business day after sending unless a notification of non delivery is received.

^^ Section 9.3 Waiver. The waiver by dOrg or Client of any breach of any of the provisions of this Agreement shall not constitute a continuing waiver or a waiver of any subsequent breach of the same or of another provision of this Agreement unless waived in writing & signed by the party against whom such waiver would be enforced. The parties waive the benefit of any rule that the Agreement is to be construed against one party or the other.

^^ Section 9.4 Severability. If any portion or provision of this Agreement is held to be invalid or unenforceable for any reason, then (i) the remaining provisions shall continue to be valid & enforceable & (ii) if by limiting such provision it would become valid & enforceable, then such provision shall be deemed to be written, construed, & enforced as so limited.

^^ Section 9.5 Precedence In the event of any conflicting terms between these Terms & Conditions & the SOW, the provisions of these Terms & Conditions will take precedence over the provisions of the SOW unless such conflicting terms were expressly drafted to take precedence & were expressly identified & approved by the DAO.

^^ Section 9.6 Governing Law. This Agreement shall be governed by & construed in accordance with the laws of the State of California without giving effect to principles of conflict of laws that would require the application of any other law. Any legal actions, claims or demands shall be handled in a court of competent jurisdiction within the State of California.

^^ Section 9.7 Entire Agreement. This Agreement contains the entire agreement of the parties & there are no other promises, conditions, understandings or other agreements, whether oral or written, relating to the subject matter of this Agreement. This Agreement may only be modified or amended with prior written approval of both parties.

^^ Section 9.8 Execution, Counterparts & Electronic Signatures. The Parties agree that the Agreement and the [[dOrg]] Standard Terms & Conditions may be executed in counterparts & each counterpart will be deemed an original & all of which together shall constitute the same document. The Parties acknowledge that the transactions contemplated under the Agreement and the [[dOrg]] Standard Terms & Conditions are conducted by electronic means & as such the Agreement and the [[dOrg]] Standard Terms & Conditions may be signed electronically & will be given the full force & effect of a binding legal contract. The Agreement and the [[dOrg]] Standard Terms & Conditions must be approved by the DAO voting protocol & signed by an authorized representative. These [[dOrg]] Standard Terms & Conditions, any amendments hereto, and the transactions contemplated hereby, are to be conducted by electronic means, and, as such, may be signed electronically, which means by any electronic sound, symbol, or process, attached to or logically associated with and executed or adopted with the intent to sign. Pursuant to this Section 9.8, the Electronic Signatures in Global and National Commerce Act, 15 U.S.C. §§ 7001 et seq., and the Uniform Electronic Transactions Act of the State of Vermont, 9 V.S.A. §§ 270 et seq., electronically-signed versions of these [[dOrg]] Terms and Conditions, the Term Sheet, any amendments hereto, and any other instruments effectuating the transactions contemplated hereby, will be recognized as and given the full force and effect of binding, legal contracts.
